const reportsMethods = require("../apiMethods/reportsMethods");

module.exports = (() => {
  const externalApiMethods = require("../apiMethods/externalApiMethods");
  const zprApiMethods = require("../apiMethods/zprMethods");
  const qrCodeMethods = require("../apiMethods/qrCodeMethods");



  return {
    Login: (req, res) => externalApiMethods.Login(req.body, res),

    getLotReports: (req, res) =>
      externalApiMethods.getLotReports(req.body, res),
    updateResultRecording: (req, res) =>
      externalApiMethods.updateResultRecording(req.body, res),
    UDsubmitResult: (req, res) =>
      externalApiMethods.UDsubmitResult(req.body, res),
    reportZQAR: (req, res) => externalApiMethods.reportZQAR(req.body, res),
    reportZQA32: (req, res) => externalApiMethods.reportZQA32(req.body, res),
    ZPRDID: (req, res) => externalApiMethods.ZPRDID(req.body, res),
    typeTest: (req, res) => externalApiMethods.typeTest(req.body, res),
    Coois: (req, res) => externalApiMethods.Coois(req.body, res),
    Co11: (req, res) => externalApiMethods.Co11(req.body, res),
    OrderInfoInwardOutward: (req, res) => externalApiMethods.OrderInfoInwardOutward(req.body, res),
    OrderInfoOutwardSave: (req, res) => externalApiMethods.OrderInfoOutwardSave(req.body, res),
    OrderInfoNonSap: (req, res) => externalApiMethods.OrderInfoNonSap(req.body, res),
    getpdb: (req, res) => externalApiMethods.getpdb(req.body, res),
    fetchzone: (req, res) => externalApiMethods.fetchzone(req.body, res),
    custgroup: (req, res) => externalApiMethods.custgroup(req.body, res),
    OrderInfoPhysicaldispatch: (req, res) => externalApiMethods.OrderInfoPhysicaldispatch(req.body, res),
    OrderInfoPlantBasedDivison: (req, res) => externalApiMethods.OrderInfoPlantBasedDivison(req.body, res),
    OrderInfoDeleteWithSap: (req, res) => externalApiMethods.OrderInfoDeleteWithSap(req.body, res),
    OrderInfoDeleteWithoutSap: (req, res) => externalApiMethods.OrderInfoDeleteWithoutSap(req.body, res),
    shipmentdetailsfetch: (req, res) => externalApiMethods.shipmentdetailsfetch(req.body, res),
    ShipmentOutwardSave: (req, res) => externalApiMethods.ShipmentOutwardSave(req.body, res),
    getTypeofmaterial: (req, res) => externalApiMethods.getTypeofmaterial(req.body, res),
    Incoterms: (req, res) => externalApiMethods.Incoterms(req.body, res),
    shipmentdetailsNonSapSave: (req, res) => externalApiMethods.shipmentdetailsNonSapSave(req.body, res),
    shipmentdetailsNonSapReports: (req, res) => externalApiMethods.shipmentdetailsNonSapReports(req.body, res),
    ShipmentDeleteWithSap: (req, res) => externalApiMethods.ShipmentDeleteWithSap(req.body, res),
    ShipmentDeleteWithoutSap: (req, res) => externalApiMethods.ShipmentDeleteWithoutSap(req.body, res),
    Shipmentchangewithsap: (req, res) => externalApiMethods.Shipmentchangewithsap(req.body, res),
    Shipmentchangewithoutsap: (req, res) => externalApiMethods.Shipmentchangewithoutsap(req.body, res),
    SegmentInfoOutwardFetch: (req, res) => externalApiMethods.SegmentInfoOutwardFetch(req.body, res),
    SegmentInfoOutwardSave: (req, res) => externalApiMethods.SegmentInfoOutwardSave(req.body, res),
    SegmentInfoNonSap: (req, res) => externalApiMethods.SegmentInfoNonSap(req.body, res),
    SegmentInfoChangeWithSap: (req, res) => externalApiMethods.SegmentInfoChangeWithSap(req.body, res),
    SegmentInfoChangeWithoutSap: (req, res) => externalApiMethods.SegmentInfoChangeWithoutSap(req.body, res),
    SegmentInfoDeleteWithSap: (req, res) => externalApiMethods.SegmentInfoDeleteWithSap(req.body, res),
    SegmentInfoDeleteWithoutSap: (req, res) => externalApiMethods.SegmentInfoDeleteWithoutSap(req.body, res),
    getssc: (req, res) => externalApiMethods.getssc(req.body, res),
    fetchTAT: (req, res) => externalApiMethods.fetchTAT(req.body, res),
    fetchNonSapTAT: (req, res) => externalApiMethods.fetchNonSapTAT(req.body, res),
    fetchzoneTat: (req, res) => externalApiMethods.fetchzoneTat(req.body, res),
    TransitInfoSave: (req, res) => externalApiMethods.TransitInfoSave(req.body, res),
    TransitInfoNonSap: (req, res) => externalApiMethods.TransitInfoNonSap(req.body, res),
    TransitInfoDeleteWithSap: (req, res) => externalApiMethods.TransitInfoDeleteWithSap(req.body, res),
    TransitInfoDeleteWithoutSap: (req, res) => externalApiMethods.TransitInfoDeleteWithoutSap(req.body, res),
    TransitInfoChangeWithSap: (req, res) => externalApiMethods.TransitInfoChangeWithSap(req.body, res),
    TransitInfoChangeWithoutSap: (req, res) => externalApiMethods.TransitInfoChangeWithoutSap(req.body, res),
    FreightBillingSave: (req, res) => externalApiMethods.FreightBillingSave(req.body, res),
    FreightBillingNonSap: (req, res) => externalApiMethods.FreightBillingNonSap(req.body, res),
    FreightBillingChangeWithSap: (req, res) => externalApiMethods.FreightBillingChangeWithSap(req.body, res),
    FreightBillingChangeWithoutSap: (req, res) => externalApiMethods.FreightBillingChangeWithoutSap(req.body, res),
    FreightBillingDeleteWithSap: (req, res) => externalApiMethods.FreightBillingDeleteWithSap(req.body, res),
    FreightBillingDeleteWithOutSap: (req, res) => externalApiMethods.FreightBillingDeleteWithOutSap(req.body, res),
    VehicleInfofetch: (req, res) => externalApiMethods.VehicleInfofetch(req.body, res),
    VehicleInfosave: (req, res) => externalApiMethods.VehicleInfosave(req.body, res),
    VehicleInfoNonSap: (req, res) => externalApiMethods.VehicleInfoNonSap(req.body, res),
    DCReferenceNo: (req, res) => externalApiMethods.DCReferenceNo(req.body, res),
    VehicleInfoMapid: (req, res) => externalApiMethods.VehicleInfoMapid(req.body, res),
    VehicleInfoMapidForNonsap: (req, res) => externalApiMethods.VehicleInfoMapidForNonsap(req.body, res),
    VehicleInfoChangeWithSap: (req, res) => externalApiMethods.VehicleInfoChangeWithSap(req.body, res),
    VehicleInfoChangeWithoutSap: (req, res) => externalApiMethods.VehicleInfoChangeWithoutSap(req.body, res),
    VehicleInfoDeleteWithSap: (req, res) => externalApiMethods.VehicleInfoDeleteWithSap(req.body, res),
    VehicleInfoDeleteWithoutSap: (req, res) => externalApiMethods.VehicleInfoDeleteWithoutSap(req.body, res),
    Invoiceloaddetailsfetch: (req, res) => externalApiMethods.Invoiceloaddetailsfetch(req.body, res),
    sapget: (req, res) => externalApiMethods.sapget(req.body, res),
    InvoiceloaddetailsSave: (req, res) => externalApiMethods.InvoiceloaddetailsSave(req.body, res),
    InvoiceloaddetailsNonSap: (req, res) => externalApiMethods.InvoiceloaddetailsNonSap(req.body, res),
    gettypeofvehicle: (req, res) => externalApiMethods.gettypeofvehicle(req.body, res),
    InvoiceloaddetailsDeleteWithsap: (req, res) => externalApiMethods.InvoiceloaddetailsDeleteWithsap(req.body, res),
    InvoiceloaddetailsDeleteWithoutsap: (req, res) => externalApiMethods.InvoiceloaddetailsDeleteWithoutsap(req.body, res),
    InsuranceClaimTrackingfetch: (req, res) => externalApiMethods.InsuranceClaimTrackingfetch(req.body, res),
    InsuranceClaimTrackingSave: (req, res) => externalApiMethods.InsuranceClaimTrackingSave(req.body, res),
    fetchinvoicelistnonsap: (req, res) => externalApiMethods.fetchinvoicelistnonsap(req.body, res),
    Nonsapsave: (req, res) => externalApiMethods.Nonsapsave(req.body, res),
    InsuranceClaimTrackingDeleteWithSap: (req, res) => externalApiMethods.InsuranceClaimTrackingDeleteWithSap(req.body, res),
    InsuranceClaimTrackingDeleteWithoutSap: (req, res) => externalApiMethods.InsuranceClaimTrackingDeleteWithoutSap(req.body, res),
    InsuranceClaimTrackingChangeWithSap: (req, res) => externalApiMethods.InsuranceClaimTrackingChangeWithSap(req.body, res),
    InsuranceClaimTrackingChangeWithoutSap: (req, res) => externalApiMethods.InsuranceClaimTrackingChangeWithoutSap(req.body, res),
    TransitDamageInfofetch: (req, res) => externalApiMethods.TransitDamageInfofetch(req.body, res),
    TransitDamageInfoSave: (req, res) => externalApiMethods.TransitDamageInfoSave(req.body, res),
    fetchinvoicelistnonsapwosp: (req, res) => externalApiMethods.fetchinvoicelistnonsapwosp(req.body, res),
    withoutsapSave: (req, res) => externalApiMethods.withoutsapSave(req.body, res),
    TransitDamageInfoDeleteWithSap: (req, res) => externalApiMethods.TransitDamageInfoDeleteWithSap(req.body, res),
    TransitDamageInfoDeleteWithoutSap: (req, res) => externalApiMethods.TransitDamageInfoDeleteWithoutSap(req.body, res),
    TransitDamageInfoChangeWithSap: (req, res) => externalApiMethods.TransitDamageInfoChangeWithSap(req.body, res),
    TransitDamageInfoChangeWithoutSap: (req, res) => externalApiMethods.TransitDamageInfoChangeWithoutSap(req.body, res),
    DispatchWithSapSave: (req, res) => externalApiMethods.DispatchWithSapSave(req.body, res),
    DispatchWithoutSapSave: (req, res) => externalApiMethods.DispatchWithoutSapSave(req.body, res),
    Dispatchf4_vendorCode: (req, res) => externalApiMethods.Dispatchf4_vendorCode(req.body, res),
    DispatchReferenceNumber: (req, res) => externalApiMethods.DispatchReferenceNumber(req.body, res),
    DispatchReferenceNumberWithoutsap: (req, res) => externalApiMethods.DispatchReferenceNumberWithoutsap(req.body, res),
    DispatchReferenceNumberEdit: (req, res) => externalApiMethods.DispatchReferenceNumberEdit(req.body, res),
    ReferenceNoFetch: (req, res) => externalApiMethods.ReferenceNoFetch(req.body, res),
    ReferenceNoFetch_Withoutsap: (req, res) => externalApiMethods.ReferenceNoFetch_Withoutsap(req.body, res),
    global_Fields_SearchOption: (req, res) => externalApiMethods.global_Fields_SearchOption(req.body, res),
    global_Fields_SearchOption_WithoutSap: (req, res) => externalApiMethods.global_Fields_SearchOption_WithoutSap(req.body, res),
    Filter_Creation: (req, res) => externalApiMethods.Filter_Creation(req.body, res),
    Filter_Creation_NonSap: (req, res) => externalApiMethods.Filter_Creation_NonSap(req.body, res),
    OrderInfoFilterCreation: (req, res) => externalApiMethods.OrderInfoFilterCreation(req.body, res),
    GlobalFilterCreationNonSap: (req, res) => externalApiMethods.GlobalFilterCreationNonSap(req.body, res),
    GlobalOutwardCountWithSap: (req, res) => externalApiMethods.GlobalOutwardCountWithSap(req.body, res),
    GlobalUserAuth: (req, res) => externalApiMethods.GlobalUserAuth(req.body, res),
    UserCreationDisplayTable: (req, res) => externalApiMethods.UserCreationDisplayTable(req.query, res),
    UserCreationDelete: (req, res) => externalApiMethods.UserCreationDelete(req.body, res),


  };
})();
